language: java
jdk: oraclejdk8
services:
- docker
branches:
  only:
  - master
script:
-  sudo chmod -R 777 db_houseskipper
- "./mvnw clean install -DskipTests -B"
before_install:
- sudo service mysql stop
- docker-compose up -d
notifications:
  slack: houseskipper:smfTiIqJXd6xCpCqeMBCqXeY
deploy:
  provider: heroku
  app: houseskipper-back
  api_key:
    secure: A62QPUpEqPvTxTelcuknNzKNw/DQP4JH3vkSY1PPEDA05nqgygYaniz8m3M8hyOw0RpJ2561YuR9A4pGcQMxAu+qOk8iWrlS8LlDdftoV3WJbhntE8v2W0e+dtGdrmMehLrElaA6bMnbreSCI7t9ePrixFtShyS6bW/wevIKR56FXwS4+1Pvyl1UyrEgMbrASJIX8kldSo5QOexlszdMSr0tr9TwsER68dbsh2KJWlkwcK1kQnm9H6P9o7ebzVaqUTSrllbuDok1/cIQETzWKvENt4Z3Dd3kxzq+Ytakb58Dh1DxqZmBzZFedp11Xa71swQxGmmI85ZmQwsd/4IX1CPzREx5o1tEinBc0Pz+pwuhOQ7HvhqvMM3YklxfhmHf4rl5lMddlLNGVdhBc13aeYYp6yaHI6r+Zg4Zi5vjgVw3zWRJx5LK/o4tlW5lcQ02TydAvz2sF9YuxiBYBZhnYZGy8uFamJdrcd+JpFFfg2X6ekTfO4ELWbG2z/VbTzlq4wjON0abCgbRIEUCML+2XBwTEPHbrGVV9AAX94OsI6ytQJojqEGQBBfU69g2Geym52eiqJ+T5j8JvUNO1eGarxvHIT/7fhraeqqHqqTgPO+NNQubrHixfIUri1hY629w7+kw9peBa9kAbUchZCmnO0gcT89TV74fckQFrHM/+cE=
