language: java
jdk: oraclejdk8
sudo: required
addons:
  ssh_known_hosts: 92.222.9.74
services:
- docker
branches:
  only:
  - master
before_deploy:
- openssl aes-256-cbc -K $encrypted_be5939367166_key -iv $encrypted_be5939367166_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
install:
- "./mvnw clean install -DskipTests -B -Dspring.profiles.active=prod"
notifications:
  slack: houseskipper:smfTiIqJXd6xCpCqeMBCqXeY
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@92.222.9.74:/deploy/houseskipper-back
  on:
    branch: master
after_deploy:
- ssh root@92.222.9.74 'chmod 777 /deploy/houseskipper-back/script.sh'
- ssh root@92.222.9.74 '/deploy/houseskipper-back/script.sh'


