
language: java
jdk: oraclejdk8
services:
- docker
branches:
  only:
  - master
script:
- "./mvnw clean install -B"

before_install:
- docker pull mysql
- docker pull phpmyadmin/phpmyadmin
- sudo service mysql stop
- docker-compose up
notifications:
  slack: houseskipper:smfTiIqJXd6xCpCqeMBCqXeY
deploy:
  provider: heroku
  api_key:
    secure: Gw3R58gk8kNYnee7N990r4eNk6GCYmq2/D8Bt08HOZoz4w+tJ+hExSIyP2YTotHE3MzfPdYSEKZwTOhLTx1DcOv0ISvmLuywGs496CBca8i7h6gO5lPCVcMPw0ryenbubRZKIEOyBqCePLZYqLgNUOFZ/fhDUB1Ni4+Ah3FH+fVMVKnMyFiVJ7BYKnvOt+PuNEZXMaW8vFTwxNKfSir36v4UC6Na8Q55rSKtiOdcIDEotQ+sQpVzDKaymDYtkDWuR66y/4fTpWyeow4DpwRfrl4CGfqRGtN6FZeAXajT4ES4D1/lmzYLk0tg18Qh0iEuD1QmhHuvpHdZ7PQgG4aoJC91rSRbuQJmFGsieLjrI2Kog6Sf+7l5UkBv8duGi1eoKKoH6qKTkDh2qFXGBXacsUun3BWV3aekTytWNC4v/gjXfC8YrlXuFPyPBiWMhshaxBHszy1LN406mfFw56+L0XRK1Px6TOC3zlOFyBfmyjrbvpvT/52pXy0nWAavZ2phc9OztRg2WBYuWBbtlnkw1arj/+3/7R6avIzyIiBclJl+O7zy90NER98tk/Y96JARXEDkxjDGizI/8TD2hVpMgkjLca+R5zxB74YskWRCF3fAE9hByYslbb2VgpxhU8ApchI81kTGCTizbky34E372tOdJh30hHn97nfRJ9/qX9s=
  app: houseskipper-back