language: java
jdk: oraclejdk8
branches:
  only:
  - master
script:
- "./mvnw clean install -B"
notifications:
  slack: houseskipper:smfTiIqJXd6xCpCqeMBCqXeY
deploy:
  provider: heroku
  api_key:
    - secure: HyMslqXtLQUGRkF1bdEhp4/n3d3QNdws1jymshU3Df2NP8kHsYO/NWFMqstcjZ2eLowRKQobNB9G+8YfN2/JkZBR2Ho7N+bCa2euwLuReLwykpXxioZzvlsgSGn8xYwHQGz/YXyT/ePejV8DVMBTvB0LAZyywRiv7nX51DtKX2o=
  app: houseskipper-back
