language: java
jdk: oraclejdk8
sudo: required
services:
- docker
branches:
  only:
  - master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_5493d0b4ffcc_key -iv $encrypted_5493d0b4ffcc_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
install:
- "./mvnw clean install -DskipTests -B -Dspring.profiles.active=prod"
notifications:
  slack: houseskipper:smfTiIqJXd6xCpCqeMBCqXeY
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@92.222.9.74:/deploy/houseskipper-back
  on:
    branch: master
after_deploy:
  - ssh root@92.222.9.74 'chmod 777 /deploy/houseskipper-back/script.sh'
  - ssh root@92.222.9.74 '/deploy/houseskipper-back/script.sh'